from pathlib import Path

from src.schemas import load_assumptions_registry

REPO_ROOT = Path(__file__).resolve().parent.parent
REGISTRY_PATH = REPO_ROOT / "config" / "assumptions_registry.json"
OUTPUT_PATH = REPO_ROOT / "docs" / "registry_summary.md"


def main() -> None:
    entries = load_assumptions_registry(REGISTRY_PATH)
    entries_sorted = sorted(entries, key=lambda e: e.tier, reverse=True)

    lines = [
        "# Assumptions registry summary",
        "",
        (
            "Generated by `scripts/generate_registry_summary.py` from "
            "`config/assumptions_registry.json` - do not edit by hand, "
            "regenerate instead so this stays in sync with the registry."
        ),
        "",
        "Sorted by tier descending (least certain first).",
        "",
        "| Parameter | Mid | Tier | Requires confirmation |",
        "| --- | --- | --- | --- |",
    ]
    for entry in entries_sorted:
        lines.append(
            f"| {entry.parameter} | {entry.value_or_range.mid} | {entry.tier} | "
            f"{entry.requires_confirmation} |"
        )
    lines.append("")

    OUTPUT_PATH.write_text("\n".join(lines))
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
