from pathlib import Path

from src.schemas import load_assumptions_registry

REPO_ROOT = Path(__file__).resolve().parent.parent
REGISTRY_PATH = REPO_ROOT / "config" / "assumptions_registry.json"
OUTPUT_PATH = REPO_ROOT / "docs" / "registry_summary.md"


def _table(entries: list) -> list[str]:
    rows = [
        "| Parameter | Mid | Tier | Requires confirmation |",
        "| --- | --- | --- | --- |",
    ]
    for entry in sorted(entries, key=lambda e: e.tier, reverse=True):
        rows.append(
            f"| {entry.parameter} | {entry.value_or_range.mid} | {entry.tier} | "
            f"{entry.requires_confirmation} |"
        )
    return rows


def main() -> None:
    entries = load_assumptions_registry(REGISTRY_PATH)
    in_scope = [e for e in entries if e.used_in_lcoe_comparison]
    out_of_scope = [e for e in entries if not e.used_in_lcoe_comparison]

    lines = [
        "# Assumptions registry summary",
        "",
        (
            "Generated by `scripts/generate_registry_summary.py` from "
            "`config/assumptions_registry.json` - do not edit by hand, "
            "regenerate instead so this stays in sync with the registry."
        ),
        "",
        (
            f"{len(entries)} parameters total; {len(in_scope)} drive the "
            f"AP1000-vs-CANDU LCOE, {len(out_of_scope)} are a future BWRX-300 SMR "
            "track not consumed by any analysis module."
        ),
        "",
        (
            "Note on in-scope provenance and known limitations: "
            "`D2O_price_usd_per_kg` and `D2O_inventory_tonnes_per_1000MWe_EC6` are "
            "not sampled directly at runtime but are the provenance of the in-scope "
            "`D2O_total_upfront_capex_usd_per_1000MWe`, while "
            "`fuel_cycle_cost_reduction_pct_CANDU_SEU_vs_natural` and "
            "`D2O_annual_makeup_losses_tonnes_per_year` are currently unused (SEU "
            "scenario retired; no annual D2O makeup in OPEX) - all four remain "
            "flagged in-scope as supporting derivations or documented known "
            "limitations rather than out-of-scope SMR parameters."
        ),
        "",
        "Each table is sorted by tier descending (least certain first).",
        "",
        "## In-scope parameters (drive AP1000-vs-CANDU LCOE)",
        "",
        *_table(in_scope),
        "",
        "## Unused / future SMR track (BWRX-300, not consumed by any analysis)",
        "",
        *_table(out_of_scope),
        "",
    ]

    OUTPUT_PATH.write_text("\n".join(lines))
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
